name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: autoreconf -i -v
    
    - name: configure
      run: ./configure LIBS=-lm

    - name: Build Package
      run: make
      
    - name: Check Tests
      run: make check

    - name: Install Package
      run: make install

    - name: Clean
      run: make clean
